---
title: "Chapter 2 Challenge Solution (R)"
format:
  html:
    code-fold: false
---

## Load libraries

```{r}
library(EIAapi)
library(dplyr)
library(lubridate)
library(plotly)
```

## Question 1

We will use the EIA API dasbhoard to extract the parameters for setting a GET request to pull the hourly demand for electricity of San Diego Gas and Electric balancing authority subregion:

```{r}
eia_api_key <- Sys.getenv("EIA_API_KEY")

api_meta_path <- "electricity/rto/region-sub-ba-data/"

api_data_path <- "electricity/rto/region-sub-ba-data/data"

frequency <- "hourly"

offset <- 0

length <- 5000

data <- "value"

facets <- list(
    parent = "CISO",
    subba = "SDGE"
)

```



```{r}
df1 <- eia_get(
    api_key = eia_api_key,
    api_path = api_data_path,
    frequency = frequency,
    data = data,
    facets = facets,
    offset = offset,
    length = length
)
```


```{r}
df1$index <- ymd_h(df1$period)

df1 <- df1 |>
    mutate(index = ymd_h(period, tz = "UTC")) |>
    select(index, everything()) |>
    arrange(index)


head(df1)
```

```{r}
plot_ly(data = df1, x = ~index, y = ~value, type = "scatter", mode = "lines")
```



## Question 2

```{r}
df2 <- eia_get(
    api_key = eia_api_key,
    api_path = api_data_path,
    frequency = frequency,
    data = data,
    facets = facets,
    offset = offset,
    length = length,
    start = "2024-01-01T01",
    end = "2024-01-31T23"
)


df2 <- df2 |>
    mutate(index = ymd_h(period, tz = "UTC")) |>
    select(index, everything()) |>
    arrange(index)
```


```{r}
plot_ly(data = df2, x = ~index, y = ~value, type = "scatter", mode = "lines")
```


## Question 3

```{r}
df3 <- eia_backfill(
    start = as.POSIXct("2020-01-01 00:00:00", tz = "UTC"),
    end = as.POSIXct("2024-02-01 00:00:00", tz = "UTC"),
    offset = 1500,
    api_key = eia_api_key,
    api_path = api_data_path,
    facets = facets
)

```